name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
  MDBOOK_VERSION: 0.4.1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./mdbook
          key: ${{ runner.os }}-${{ env.MDBOOK_VERSION }}
      - uses: actions/checkout@v2
      - name: Get mdBook
        run: curl -L --output - https://github.com/rust-lang/mdBook/releases/download/v0.4.12/mdbook-v0.4.12-x86_64-unknown-linux-gnu.tar.gz | tar -xzf - -C /usr/local/bin
      - run: mdbook build
